service: auth-service

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "arn:aws:logs:*:*:*"
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:Scan
            - dynamodb:Query
          Resource: "arn:aws:dynamodb:eu-west-1:*:table/UsersTable"

functions:
  signUp:
    handler: handler.signUp
    events:
      - http:
          path: signup
          method: post
          cors:
            origin: "*" # Allow all origins (or specify your domain)
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false

  login:
    handler: handler.login
    events:
      - http:
          path: login
          method: post
          cors:
            origin: "*" # Allow all origins (or specify your domain)
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UsersTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
